server:
  port: 8087

# spring:
#   application:
#     name: temporal-demo
#   datasource:
#     url: jdbc:postgresql://localhost:5432/bisbis10
#     username: postgres
#     password: root
#     driverClassName: org.postgresql.Driver
#     platform: postgres
#   jpa:
#     database: POSTGRESQL
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#   sql:
#     init:
#       mode: always

# DataSource configuration for H2
spring:
  datasource:
    url: jdbc:h2:mem:bisbis
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console